-- 코드를 작성해주세요
select count(FISH_INFO.FISH_TYPE) as FISH_COUNT
from FISH_INFO , FISH_NAME_INFO 
where FISH_INFO.FISH_TYPE=FISH_NAME_INFO.FISH_TYPE and (FISH_NAME like 'BASS' or FISH_NAME like 'SNAPPER')
