-- 코드를 입력하세요
SELECT b.BOOK_ID, a.AUTHOR_NAME, DATE_FORMAT(b.PUBLISHED_DATE,"%Y-%m-%d") AS PUBLISHED_DATE
from BOOK b join AUTHOR a on b.AUTHOR_ID = a.AUTHOR_ID
WHERE b.CATEGORY like '경제'
ORDER BY PUBLISHED_DATE
